# Generated by Django 5.2.7 on 2025-11-23 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('vailed_from', models.DateTimeField()),
                ('vailed_to', models.DateTimeField()),
                ('discount', models.FloatField(help_text='discount percentage between 0 and 100', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
