# Generated by Django 5.2.7 on 2025-10-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
