# Generated by Django 5.2.7 on 2025-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpayment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='orderpayment',
            name='orders_orde_timesta_48b3dc_idx',
        ),
        migrations.RenameField(
            model_name='orderpayment',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='pay_image',
            field=models.ImageField(upload_to='vodfonecash/'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['-created'], name='orders_orde_created_256645_idx'),
        ),
    ]
