# Generated by Django 5.2.7 on 2025-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='pay_phone',
            field=models.CharField(max_length=11),
        ),
    ]
