# Generated by Django 5.2.7 on 2025-11-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderpayment_pay_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='product',
        ),
    ]
